### ISSUE TITLE
Launch karma

### ISSUE THREAD

**Issue by hadrienl** [zewa666/angular_es6#8]
Hello,

I'm back with a new project with angular after a year with Aurelia. I'd like to work again with this foundation which was very good but I can't launch tests anymore. When I start karma with `karma start` I have the following error :

```
karma start
(node:23916) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:jspm"! (Resolving: framework:jspm)
  at error (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:22:12)
  at Object.parent.get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:9:13)
  at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
  at /usr/local/lib/node_modules/karma/lib/server.js:29:14
  at Array.forEach (native)
  at start (/usr/local/lib/node_modules/karma/lib/server.js:28:21)
  at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
  at Object.exports.start (/usr/local/lib/node_modules/karma/lib/server.js:307:12)
  at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:220:27)
  at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
  at Module._compile (module.js:541:32)
  at Object.Module._extensio%
```

Do you know how to fix this ?

**Comment by hadrienl** [comment]
I've updated all packages and followed this : https://github.com/Workiva/karma-jspm but I still get the same error :(

**Comment by hadrienl** [comment]
Well… I've tried with local binary (`./node_modules/.bin/karma start`) and it worked… so nevermind.

I'll try to update all project to work with babel 6 and with [this configuration](https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul). Help should be very appreciated ;)

**Comment by hadrienl** [comment]
I've retried with a fresh master state and I have this error :

```
Uncaught Error loading "jspm_packages/github/angular/bower-angular@1.4.7/angular" at /Users/hadrien/Documents/dev/angular-babel/angular_es6/dist/jspm_packages/github/angular/bower-angular@1.4.7/angular
  Not Found: /Users/hadrien/Documents/dev/angular-babel/angular_es6/dist/jspm_packages/github/angular/bower-angular@1.4.7/angular
  at /Users/hadrien/Documents/dev/angular-babel/angular_es6/node_modules/karma-jspm/src/adapter.js:59
```

**Comment by hadrienl** [comment]
Well, I've set up a new project… https://github.com/hadrienl/angular-jspm-babel-6
